name: Test

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        versions:
          - { python: '3.5', os: 'ubuntu-20.04' }
          - { python: '3.6', os: 'ubuntu-20.04' }
          - { python: '3.7', os: 'ubuntu-latest' }
          - { python: '3.8', os: 'ubuntu-latest' }
          - { python: '3.9', os: 'ubuntu-latest' }
          - { python: '3.10', os: 'ubuntu-latest' }
          - { python: '3.11', os: 'ubuntu-latest' }
          - { python: '3.12', os: 'ubuntu-latest' }
          # pypy
          - { python: 'pypy-3.6', os: 'ubuntu-latest' }
          - { python: 'pypy-3.7', os: 'ubuntu-latest' }
          - { python: 'pypy-3.8', os: 'ubuntu-latest' }
          - { python: 'pypy-3.9', os: 'ubuntu-latest' }
          # etc
          - { python: 'graalpy-23.1', os: 'ubuntu-latest' }

    runs-on: ${{ matrix.versions.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}
      - run: pipx install hatch
      - run: hatch run test
